name: deploy docs to gh-page

on:
  push:
    branches: [master, main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install tox
        run: pip install --upgrade tox
      - name: setup pages
        uses: actions/configure-pages@v2
      - name: build docs
        run: tox -e docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _build/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy to gh-pages
        id: deployment
        uses: actions/deploy-pages@v1
